version: '3.1'

services:

  api:
    build:
      dockerfile: Dockerfile-backend
      context: .
    ports:
      - 8081:8081

  front:
    build:
      dockerfile: Dockerfile-frontend
      context: .
    ports:
      - 3000:3000